


export const USER_LOADING ='USER_LOADING'
export const USER_LOADED ='USER_LOADED'
export const AUTH_ERROR ='AUTH_ERROR'
export const LOGIN_SUCCES='LOGIN_SUCCES'
export const LOGIN_FAUL='LOGIN_FAUL'
export const REGISTER_SUCCESS ='REGISTER_SUCCESS'
export const REGISTER_FAUL ='REGISTER_FAUL'
export const GET_ERROR ='GET_ERROR'
export const CLEAR_ERROR ='CLEAR_ERROR'